version: '3'

services:
  web:
    build: .
    container_name: fastapi-test
    ports:
      - "8000:8000"
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 test_app/create_db.py; uvicorn test_app.main:app --host 0.0.0.0'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db_tasks
    depends_on:
      - db
    volumes:
      - .:/test_app

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_tasks

volumes:
  postgres_data: